[usuarios]
LOGIN1 = { LOGIN = "admin", SENHA = "123" }
LOGIN2 = { LOGIN = "user", SENHA = "456" }

[default]
CLIENT_ID = "xxxxxxxxx"
CLIENT_SECRET = "xxxxxxxxx"
TENANT_ID = "xxxxxxxxx"
SITE_DOMAIN = "xxxxxxxxx"
SITE_NAME = "xxxxxxxxx"
LIST_NAME = "xxxxxxxxx"
